[project]
name = "fast-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ohmartin", email = "ohmartin@bancolombia.com.co" }
]
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=4.0.11",
    "httpx>=0.27.0",
    "truststore>=0.9.1",
]

[project.scripts]
fast-mcp = "fast_mcp:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
